"""
Phase 3B (PHASE C) — Validate the daily GRAP state table.

Input:  data/raw/grap/grap_events_manual.csv (verified events)
        data/processed/daily_grap_state.csv (generated by 06_build_daily_grap_state.py)

Output: reports/data_quality/grap_daily_validation.md

Checks:
  1. No duplicate dates
  2. No missing dates (continuous 2022-01-01 to 2023-12-31)
  3. Correct chronological ordering
  4. Every event date transitions to the expected stage
  5. The day before an event retains the previous stage
  6. Every stage transition matches the verified event table
"""
from __future__ import annotations

import os
import sys
from datetime import date, timedelta
from pathlib import Path

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import config as C


def validate_daily_grap_state() -> dict:
    """Run all validation checks. Return findings dict."""
    findings = {
        "checks_passed": [],
        "checks_failed": [],
        "data_overview": {},
    }

    try:
        daily_df = pd.read_csv(C.DAILY_GRAP_STATE_CSV)
        events_df = pd.read_csv(C.GRAP_EVENTS_CSV, dtype=str, keep_default_na=False)
    except FileNotFoundError as e:
        findings["checks_failed"].append(f"Input file missing: {e}")
        return findings

    # Parse dates
    daily_df["date"] = pd.to_datetime(daily_df["date"]).dt.date
    events_df = events_df[events_df["verified"].astype(str).str.strip() == "Yes"].copy()
    events_df["effective_date"] = pd.to_datetime(events_df["effective_date"]).dt.date

    # =====================================================================
    # CHECK 1: No duplicate dates
    # =====================================================================
    duplicates = daily_df[daily_df.duplicated(subset=["date"], keep=False)]
    if len(duplicates) == 0:
        findings["checks_passed"].append("CHECK 1: No duplicate dates")
    else:
        findings["checks_failed"].append(
            f"CHECK 1 FAILED: Found {len(duplicates)} duplicate date(s): "
            f"{duplicates['date'].unique()[:5]}"
        )

    # =====================================================================
    # CHECK 2: No missing dates (continuous range)
    # =====================================================================
    dates_set = set(daily_df["date"])
    expected_start = date(2022, 1, 1)
    expected_end = date(2023, 12, 31)
    expected_count = (expected_end - expected_start).days + 1

    current = expected_start
    missing_dates = []
    while current <= expected_end:
        if current not in dates_set:
            missing_dates.append(current)
        current += timedelta(days=1)

    if len(missing_dates) == 0:
        findings["checks_passed"].append(
            f"CHECK 2: No missing dates ({len(dates_set)} consecutive dates)"
        )
    else:
        findings["checks_failed"].append(
            f"CHECK 2 FAILED: Found {len(missing_dates)} missing date(s): "
            f"{missing_dates[:5]}"
        )

    # =====================================================================
    # CHECK 3: Correct chronological ordering
    # =====================================================================
    daily_sorted = daily_df.sort_values("date").reset_index(drop=True)
    if daily_sorted["date"].equals(daily_df["date"]):
        findings["checks_passed"].append("CHECK 3: Dates in chronological order")
    else:
        findings["checks_failed"].append(
            "CHECK 3 FAILED: Dates not in chronological order"
        )

    # =====================================================================
    # CHECK 4: Event dates have expected stage transitions
    # =====================================================================
    event_checks_passed = 0
    event_checks_failed = []

    for _, evt in events_df.iterrows():
        evt_date = evt["effective_date"]
        expected_stage = int(float(evt["stage_to"]))
        evt_id = evt["event_id"].strip()

        evt_row = daily_df[daily_df["date"] == evt_date]
        if len(evt_row) == 0:
            event_checks_failed.append(
                f"Event {evt_id} ({evt_date}): date not found in daily table"
            )
        else:
            actual_stage = evt_row.iloc[0]["grap_stage"]
            if actual_stage == expected_stage:
                event_checks_passed += 1
            else:
                event_checks_failed.append(
                    f"Event {evt_id} ({evt_date}): expected stage {expected_stage}, "
                    f"got {actual_stage}"
                )

    if len(event_checks_failed) == 0:
        findings["checks_passed"].append(
            f"CHECK 4: All {event_checks_passed} event dates have correct stage"
        )
    else:
        findings["checks_failed"].extend([f"CHECK 4 FAILED: {msg}" for msg in event_checks_failed])

    # =====================================================================
    # CHECK 5: Day before event retains previous stage
    # =====================================================================
    day_before_checks_passed = 0
    day_before_checks_failed = []

    for _, evt in events_df.iterrows():
        evt_date = evt["effective_date"]
        expected_prev_stage = int(float(evt["stage_from"]))
        evt_id = evt["event_id"].strip()
        day_before = evt_date - timedelta(days=1)

        db_row = daily_df[daily_df["date"] == day_before]
        if len(db_row) == 0:
            # Day before might be off-season or out of range; skip
            continue
        else:
            actual_prev_stage = db_row.iloc[0]["grap_stage"]
            if actual_prev_stage == expected_prev_stage:
                day_before_checks_passed += 1
            else:
                day_before_checks_failed.append(
                    f"Event {evt_id} ({evt_date}): day before ({day_before}) "
                    f"expected stage {expected_prev_stage}, got {actual_prev_stage}"
                )

    if len(day_before_checks_failed) == 0:
        findings["checks_passed"].append(
            f"CHECK 5: All {day_before_checks_passed} pre-event days retain previous stage"
        )
    else:
        findings["checks_failed"].extend([f"CHECK 5 FAILED: {msg}" for msg in day_before_checks_failed])

    # =====================================================================
    # CHECK 6: Stage continuity (no unexplained jumps)
    # =====================================================================
    continuity_issues = []
    for i in range(1, len(daily_sorted)):
        prev_row = daily_sorted.iloc[i - 1]
        curr_row = daily_sorted.iloc[i]

        prev_stage = prev_row["grap_stage"]
        curr_stage = curr_row["grap_stage"]
        is_event_day = curr_row["is_event_day"]

        # If not an event day, stage should match previous day (within same season)
        if not is_event_day and prev_row["season"] == curr_row["season"]:
            if prev_stage != curr_stage:
                continuity_issues.append(
                    f"Non-event day {curr_row['date']}: stage jumped from "
                    f"{prev_stage} to {curr_stage} (not an event day)"
                )

    if len(continuity_issues) == 0:
        findings["checks_passed"].append("CHECK 6: No unexplained stage jumps")
    else:
        findings["checks_failed"].extend([f"CHECK 6 FAILED: {msg}" for msg in continuity_issues[:5]])

    # =====================================================================
    # Data overview
    # =====================================================================
    findings["data_overview"] = {
        "total_rows": len(daily_df),
        "date_range": f"{daily_df['date'].min()} to {daily_df['date'].max()}",
        "in_season_rows": len(daily_df[daily_df["season"].notna()]),
        "off_season_rows": len(daily_df[daily_df["season"].isna()]),
        "unique_stages": sorted(daily_df["grap_stage"].unique()),
        "event_days": len(daily_df[daily_df["is_event_day"] == 1]),
        "verified_events": len(events_df),
    }

    return findings


def write_report(findings: dict) -> None:
    """Write validation report to Markdown."""
    report_dir = Path(C.REPORTS_DQ_DIR)
    report_dir.mkdir(parents=True, exist_ok=True)
    report_path = report_dir / "grap_daily_validation.md"

    lines = [
        "# GRAP Daily State Table Validation Report",
        "",
        "## Data Overview",
        "",
    ]

    overview = findings["data_overview"]
    if overview:
        lines.extend([
            f"- **Total rows**: {overview.get('total_rows', 'N/A')}",
            f"- **Date range**: {overview.get('date_range', 'N/A')}",
            f"- **In-season rows**: {overview.get('in_season_rows', 'N/A')}",
            f"- **Off-season rows**: {overview.get('off_season_rows', 'N/A')}",
            f"- **Unique GRAP stages**: {overview.get('unique_stages', 'N/A')}",
            f"- **Event days**: {overview.get('event_days', 'N/A')}",
            f"- **Verified events**: {overview.get('verified_events', 'N/A')}",
            "",
        ])

    lines.extend([
        "## Validation Checks",
        "",
        "### Passed",
        "",
    ])

    for msg in findings["checks_passed"]:
        lines.append(f"- {msg}")

    lines.extend([
        "",
        "### Failed",
        "",
    ])

    if findings["checks_failed"]:
        for msg in findings["checks_failed"]:
            lines.append(f"- {msg}")
    else:
        lines.append("- None")

    lines.extend([
        "",
        "## Assumptions & Limitations",
        "",
        "1. **Season scoping**: GRAP stages are scoped per season (Oct 1 – Feb 28/29).",
        "2. **Off-season data**: Off-season dates (Mar–Sep) have `season=NULL` and no stage concept.",
        "3. **Event-day logic**: An event date takes the `stage_to` value immediately.",
        "4. **No extrapolation**: After E009 (2022-12-30), stage remains 3 to season end (2023-02-28).",
        "   - Season 2023-24 (Oct 2023 – Feb 2024) is marked but has no events and falls outside",
        "   - the loaded data window (ends 2023-12-31). This is a known data-completeness gap, not an error.",
        "",
        "## Summary",
        "",
        f"**Passed**: {len(findings['checks_passed'])} / {len(findings['checks_passed']) + len(findings['checks_failed'])}",
        "",
    ])

    report_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Report written to {report_path}")


def main() -> int:
    findings = validate_daily_grap_state()
    write_report(findings)

    # Print summary
    n_passed = len(findings["checks_passed"])
    n_failed = len(findings["checks_failed"])
    print(f"\n{'='*60}")
    print(f"Validation Summary: {n_passed} passed, {n_failed} failed")
    print(f"{'='*60}")

    if findings["checks_passed"]:
        print("\nPassed:")
        for msg in findings["checks_passed"]:
            print(f"  [OK] {msg}")

    if findings["checks_failed"]:
        print("\nFailed:")
        for msg in findings["checks_failed"]:
            print(f"  [FAIL] {msg}")
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
